### ISSUE TITLE
entropy security

### ISSUE THREAD

**Issue by zack-bitcoin** [tallakt/veoanity#1]
https://github.com/tallakt/veoanity/blob/master/veoanity.exs#L16
I notice you are using the rand library for entropy for making private keys.
I think this might not be good enough. It is my understanding that this library was not designed for cryptographically secure randomness.
I recommend using crypto strong_rand_bytes. 
http://erlang.org/doc/man/crypto.html#strong_rand_bytes-1
This is the library that I use to generate entropy in the full node.

**Comment by tallakt** [comment]
I will fix this quite soon. Thanks for the heads up

**Comment by tallakt** [comment]
Fixed in 44506fc60c3299837e4e04b75edd374c30e738f2
